name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      MAVEN_HOME: /opt/maven
      DOCKER_REGISTRY: 18.118.36.159:8082
      DOCKER_IMAGE: my-app
      NEXUS_CREDENTIALS: ${{ secrets.NEXUS_CREDENTIALS }}

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'adopt'  # Specify the distribution here

    - name: Build with Maven
      run: mvn clean install

    - name: Unit Testing
      run: mvn test

    - name: Functional Testing
      run: mvn verify -DtestSuite=functional

    - name: Performance Testing
      run: mvn verify -DtestSuite=performance

    - name: Build Docker Image
      run: docker build -t ${{ env.DOCKER_REGISTRY }}/repository/test/${{ env.DOCKER_IMAGE }}:latest .

    - name: Docker Login & Push to Nexus
      run: |
        echo ${{ secrets.NEXUS_CREDENTIALS }} | docker login ${{ env.DOCKER_REGISTRY }} -u admin --password-stdin
        docker push ${{ env.DOCKER_REGISTRY }}/repository/test/${{ env.DOCKER_IMAGE }}:latest
